### ISSUE TITLE
Flash Player DLA no longer works

### ISSUE THREAD

**Issue by aysiu** [autopkg/jazzace-recipes#2]
Adobe switched it up so you have to log in before you can download.

**Comment by jazzace** [comment]
Thanks for this. Away for a few days, so I'll see what I can do next week.

Anthony Reimer
Sent from my iPad

On Oct 13, 2016, at 3:14 PM, A.Y. Siu <notifications@github.com<mailto:notifications@github.com>> wrote:

Adobe switched it up so you have to log in before you can download.

##

**Comment by aysiu** [comment]
Thanks, @jazzace. Not sure if there's a good fix. Do we want people storing their Adobe ID credentials (I guess if they set up a dummy account that _only_ fetches Flash)?

**Comment by jazzace** [comment]
I was not able to recreate your problem. When we entered into a distribution license agreement (DLA) with Adobe, they provided us with a unique URL that included our authorization code (similar in form to an Adobe serial number). I put that URL in my override and it worked fine. Tested the URL without AutoPkg today and it worked as expected. I understand that you must authenticate with an Adobe ID to apply for a DLA, but I have not been required to login to download the Flash installer once my agreement has been approved.

**Comment by aysiu** [comment]
That's how it worked for me before, but suddenly my unique URL stopped working. I requested a new authorization, and I got another URL... and the URL worked fine, but only after I authenticated. By agreement, we can't share the URLs we get from Adobe. Anyone else experiencing this? I think someone else on Slack was having this problem as well... Edit: I think you're Slack, right?
https://macadmins.slack.com/archives/autopkg/p1476393416002205

**Comment by jazzace** [comment]
My licensing agreement just expired, so I have now experienced the same problem that you did. My conclusion is that sometime in October 2016, Adobe changed their URL scheme. If you have a personally-unique URI, it (and the AdobeFlashPlayerDLACurrent recipes) will work until the DLA expires. Once you renew, you are given a new, non-unique URI that requires authentication with the Adobe ID you used for the agreement.

So I have documented this in the AdobeFlashPlayerDLACurrent and will leave them up for the next year. I will look at coming up with a new set of recipes to deal with Adobe's new rules, but with Flash in a death spiral, I'm not going to spend much time on this, especially since we have a working workaround in the main autopkg recipes repo.
