### ISSUE TITLE
Processing 4 Support

### ISSUE THREAD

**Issue by jshirle2** [autopkg/jazzace-recipes#28]
Just requesting that the Processing.pkg.recipe grab the version 4 now that that is the current branch. 

Thanks!

**Comment by jazzace** [comment]
Since Processing 4 has moved to a new repository, either a new recipe will need to be written for the downloading or the current one will need to be updated and versions 1-3 abandoned. My pkg recipe uses the download recipe from timsutton-recipes, so there is nothing to change in my recipe. You'll need to file your issue with Tim (or write your own Processing 4 recipes, since I am no longer deploying Processing and I doubt Tim is any more).

**Comment by jazzace** [comment]
As it turned out, I had a request to deploy Processing, so I have now added recipes for Processing 4, @jshirle2.
