### ISSUE TITLE
Office2011Updates.ds copying to DS repo every run

### ISSUE THREAD

**Issue by grahampugh** [autopkg/jazzace-recipes#3]
The Office2011Updates.ds is downloading every time AutoPkg runs. The verbose run appears to suggest that nothing is downloaded from the source, it is just copying to the DS repo every time. I'm not sure why. 

This doesn't happen with other .ds recipes I use. 
[output.txt](https://github.com/autopkg/jazzace-recipes/files/550218/output.txt)

(I use an override to change the destination path but nothing else.)
[MSOffice2011Updates.ds.recipe.txt](https://github.com/autopkg/jazzace-recipes/files/550226/MSOffice2011Updates.ds.recipe.txt)

**Comment by jazzace** [comment]
In looking at your log and in my own testing, the item is not being copied to the DS repo each time, only to the AutoPkg cache. The .ds part of the recipe appears to be functioning as designed (i.e. the StopProcessingIf processor is doing its job). You may wish to file an issue with the parent recipe (main autopkg recipe repo), as the copy within the cache seems to be related to the CodeSignatureVerifier needing a copy to do its work. The package gets overwritten each time in that cache, so it may be considered expected behaviour, but that's not for me to answer.

**Comment by grahampugh** [comment]
I don't think any AutoPkg recipe would have expected behaviour of doing something when nothing has changed at any point of the chain (origin, cache, destination). And certainly not to report an update on every run. But fair enough, I'll look at the parent recipe.
