### ISSUE TITLE
Sassafras Download URL changed

### ISSUE THREAD

**Issue by vmiller** [autopkg/jazzace-recipes#32]
The Sassafras download recipes have been failing with a 404 error.  I had a chance to poke around a little to see what the new URL looks like.

The new URL is in the form of https://www.sassafras.com/links/ksp-client-79-latest.pkg

Possible approaches to fix : 
- Go back to something similar to the older SassafrasK2.download recipe where "REVISION" is set 
- Scrape http://www.sassafras.com/client-download/ for the download link.

Also, I don't see a public download link for the server software anymore just client and admin.  

I may have some time this week to poke around at potential fixes.

**Comment by jazzace** [comment]
Thanks for the heads up. I think this is worth me making a call to Sassafras. This is a company that might actually care about making this accessible to us via automation.

**Comment by vmiller** [comment]
That thought crossed my mind as well.  They are a small outfit as well, so you can talk to someone with some influence :-)

**Comment by jazzace** [comment]
I think I found the problem. The downloads are still there, but they changed the capitalization on MacOS [sic] and Server in the earlier part of the URL. I can make a fix but it will require an extra processor to deal with the capitalization (since the package is still lower case). Sidebar: I can get to the downloads page if it is called from the Admin console but it gets redirected to the client download page [HTTP, surprisingly] if I enter that same URL (https://www.sassafras.com/downloads/) in a browser directly.

**Comment by jazzace** [comment]
Based on my interaction with Sassafras tech support, I will probably wait until late today to see if they change the URLs back to lower case before writing the fix. They did confirm that the main Downloads page redirects unless you are logged in (which lays a cookie down) or you are coming from the Admin client.

**Comment by jazzace** [comment]
Sassafras has confirmed that this naming standards change will persist (it was an internal process cleanup that had an unintended consequence to us). The [download recipe has been updated](https://github.com/autopkg/jazzace-recipes/blob/master/Sassafras/SassafrasAllSight.download.recipe) to reflect the change. This recipe now requires the dataJAR-recipes repo.
