### ISSUE TITLE
DiffusionBee Download URL Not Found

### ISSUE THREAD

**Issue by kclose3** [autopkg/jazzace-recipes#37]
No match found on URL: https://diffusionbee.com/download
Failed.

Failed for both ARCH_HQ: Intel and ARM

**Comment by jazzace** [comment]
The developer has made a couple of changes to download file naming, has eliminated the separate HQ version, and the app's code signature has changed. The recipe has been updated to account for these changes. However, this also meant that one of the input variables had to change. Because this change broke existing overrides, I chose to change the input variable name as well (from ARCH_HQ to ARCH). You will need to change (or rebuild) your override(s).
